"""扩容素材：把 Demo 的 17 人扩到 55 人（规范 §47–§51 的补充数据源）。

这里和 :mod:`app.seed_data` 一样是**纯数据**，不含任何函数与计算逻辑，
写入流程仍然在 :mod:`app.seed`。四块内容各管一件事：

* :data:`EXTRA_GROUPS` —— 在原有 5 个星系（宿舍 / 摄影社 / 实验室 / 高中 / 家人）
  之外新增 8 个，``sort_order`` 从 5 接着往下排；
* :data:`EXTRA_PEOPLE` —— 41 个人。``activity`` 是这批数据新增的字段，
  它描述"最近还有没有来往"这个事实本身，取值 ``hot`` / ``warm`` / ``cooling`` /
  ``cold``，只用于装配阶段挑互动素材，**不参与任何评分或排序**；
* :data:`THEMED_INTERACTIONS` —— 按主题分组的互动内容池。句子刻意不写人名，
  也不写"他 / 她 / 我 / 你"，同一句可以落给任何人，装配时再按人名拼接；
* :data:`SOLO_INTERACTIONS` —— 一个人自己的 24 条记录，用 ``SELF_PERSON_KEY``
  那一行承载（键名与 :mod:`app.seed_data` 保持一致）；
* :data:`EXTRA_PLACES` —— 互动 ``location`` 可用的地点名，和既有地点不重复。

语气约定（规范 §20）：只写用户自己记下的生活片段，平静、具体。
不写情绪评价、不写关系评分、不写亲密度、不写"该联系一下了"。
"""

from __future__ import annotations

from typing import Any

#: 与 :data:`app.seed_data.SELF_PERSON_KEY` 相同的占位键：指代"我"自己。
SELF_PERSON_KEY = "__self__"

#: 新增 8 个星系；``icon`` 取自前端内置图标集。
EXTRA_GROUPS: list[dict[str, Any]] = [
    {"name": "同事", "icon": "briefcase", "sort_order": 5},
    {"name": "老同学", "icon": "book", "sort_order": 6},
    {"name": "健身房", "icon": "dumbbell", "sort_order": 7},
    {"name": "读书会", "icon": "palette", "sort_order": 8},
    {"name": "乐队", "icon": "music", "sort_order": 9},
    {"name": "邻居", "icon": "users", "sort_order": 10},
    {"name": "客户", "icon": "gamepad", "sort_order": 11},
    {"name": "咖啡馆", "icon": "coffee", "sort_order": 12},
]

#: 41 个人。``met_at`` 从 2017 铺到 2025，``activity`` 的分布见模块文档。
EXTRA_PEOPLE: list[dict[str, Any]] = [
    # --- hot（10 人，最近一次互动在 0–6 天前）---
    {
        "name": "沈亦",
        "relationship_label": "同事",
        "groups": ["同事"],
        "circle_level": "frequent",
        "met_at": (2019, 7, 3),
        "avatar": "star",
        "activity": "hot",
        "notes": "工位在窗边，下午总泡一杯茶。",
    },
    {
        "name": "顾之遥",
        "relationship_label": "读书会同好",
        "groups": ["读书会"],
        "circle_level": "normal",
        "met_at": (2025, 3, 22),
        "avatar": "comet",
        "activity": "hot",
        "notes": "借书总用一张便签夹着还回来。",
    },
    {
        "name": "裴照",
        "relationship_label": "健身房认识",
        "groups": ["健身房"],
        "circle_level": "normal",
        "met_at": (2023, 10, 11),
        "avatar": "mountain",
        "activity": "hot",
        "notes": "练背的日子会提前在群里说一声。",
    },
    {
        "name": "钱多多",
        "relationship_label": "邻居",
        "groups": ["邻居"],
        "circle_level": "normal",
        "met_at": (2022, 4, 2),
        "avatar": "cat",
        "activity": "hot",
        "notes": "楼下遛一只橘猫，会在门口停一会儿。",
    },
    {
        "name": "叶蓝",
        "relationship_label": "大学同学",
        "groups": ["老同学"],
        "circle_level": "frequent",
        "met_at": (2019, 9, 5),
        "avatar": "wave",
        "activity": "hot",
        "notes": "论文写到一半就去做饭。",
    },
    {
        "name": "田晓",
        "relationship_label": "乒乓球搭子",
        "groups": ["健身房"],
        "circle_level": "normal",
        "met_at": (2024, 6, 15),
        "avatar": "cat",
        "activity": "hot",
        "notes": None,
    },
    {
        "name": "许青禾",
        "relationship_label": "研究生同学",
        "groups": ["老同学"],
        "circle_level": "frequent",
        "met_at": (2024, 9, 1),
        "avatar": "leaf",
        "activity": "hot",
        "notes": "总在群里发食堂的当日菜单。",
    },
    {
        "name": "罗一舟",
        "relationship_label": "咖啡馆老板",
        "groups": ["咖啡馆"],
        "circle_level": "normal",
        "met_at": (2021, 5, 20),
        "avatar": "coffee",
        "activity": "hot",
        "notes": "认得常客的口味，不问就上。",
    },
    {
        "name": "陆离",
        "relationship_label": "乐队成员",
        "groups": ["乐队"],
        "circle_level": "frequent",
        "met_at": (2020, 11, 7),
        "avatar": "star",
        "activity": "hot",
        "notes": "调音要调很久，鼓凳上总放一件外套。",
    },
    {
        "name": "高野",
        "relationship_label": "表弟",
        "groups": ["家人"],
        "circle_level": "core",
        "met_at": (2017, 2, 12),
        "avatar": "bird",
        "activity": "hot",
        "notes": "暑假在准备考研，问我借了几本参考书。",
    },
    # --- warm（12 人，最近一次互动在 20–70 天前）---
    {
        "name": "姜屿白",
        "relationship_label": "前同事",
        "groups": ["同事"],
        "circle_level": "normal",
        "met_at": (2020, 3, 9),
        "avatar": "camera",
        "activity": "warm",
        "notes": "离职以后还留着原来的工牌挂绳。",
    },
    {
        "name": "白露",
        "relationship_label": "研究生同学",
        "groups": ["老同学"],
        "circle_level": "normal",
        "met_at": (2023, 9, 12),
        "avatar": "moon",
        "activity": "warm",
        "notes": None,
    },
    {
        "name": "周予安",
        "relationship_label": "羽毛球搭子",
        "groups": ["健身房"],
        "circle_level": "frequent",
        "met_at": (2022, 8, 19),
        "avatar": "cactus",
        "activity": "warm",
        "notes": "羽毛球打得很好，总约周末。",
    },
    {
        "name": "岑野",
        "relationship_label": "爬山认识",
        "groups": ["健身房"],
        "circle_level": "occasional",
        "met_at": (2021, 6, 6),
        "avatar": "mountain",
        "activity": "warm",
        "notes": "包里常年带着一副护膝。",
    },
    {
        "name": "汤圆",
        "relationship_label": "大学室友",
        "groups": ["宿舍"],
        "circle_level": "frequent",
        "met_at": (2018, 9, 8),
        "avatar": "cactus",
        "activity": "warm",
        "notes": "养了六盆多肉，名字都起好了。",
    },
    {
        "name": "谢云归",
        "relationship_label": "客户对接人",
        "groups": ["客户"],
        "circle_level": "normal",
        "met_at": (2024, 1, 15),
        "avatar": "leaf",
        "activity": "warm",
        "notes": "邮件结尾永远是一句简短的道谢。",
    },
    {
        "name": "范知秋",
        "relationship_label": "读书会发起人",
        "groups": ["读书会"],
        "circle_level": "normal",
        "met_at": (2023, 11, 30),
        "avatar": "book",
        "activity": "warm",
        "notes": "挑书偏冷门，每次都会带两本备选。",
    },
    {
        "name": "严晓",
        "relationship_label": "研究生同学",
        "groups": ["老同学"],
        "circle_level": "normal",
        "met_at": (2022, 9, 3),
        "avatar": "leaf",
        "activity": "warm",
        "notes": "做实验习惯把步骤写在白板上。",
    },
    {
        "name": "唐果",
        "relationship_label": "表姐",
        "groups": ["家人"],
        "circle_level": "frequent",
        "met_at": (2017, 8, 20),
        "avatar": "star",
        "activity": "warm",
        "notes": "孩子刚上幼儿园，朋友圈全是手工课。",
    },
    {
        "name": "温言",
        "relationship_label": "楼下便利店老板",
        "groups": ["邻居"],
        "circle_level": "occasional",
        "met_at": (2020, 12, 1),
        "avatar": "coffee",
        "activity": "warm",
        "notes": "记得常买的酸奶是哪个牌子。",
    },
    {
        "name": "苏木",
        "relationship_label": "乐队成员",
        "groups": ["乐队"],
        "circle_level": "normal",
        "met_at": (2021, 4, 17),
        "avatar": "comet",
        "activity": "warm",
        "notes": "排练总迟到十分钟，但从不缺席。",
    },
    {
        "name": "林昀",
        "relationship_label": "高中同桌",
        "groups": ["高中"],
        "circle_level": "normal",
        "met_at": (2017, 9, 1),
        "avatar": "book",
        "activity": "warm",
        "notes": "高考完一起去过一趟海边。",
    },
    # --- cooling（10 人，最近一次互动在 100–220 天前）---
    {
        "name": "老赵",
        "relationship_label": "房东",
        "groups": ["邻居"],
        "circle_level": "occasional",
        "met_at": (2021, 3, 1),
        "avatar": "moon",
        "activity": "cooling",
        "notes": "收房租只收现金，水龙头坏了打一个电话就来。",
    },
    {
        "name": "方雨",
        "relationship_label": "支教时认识",
        "groups": ["老同学"],
        "circle_level": "occasional",
        "met_at": (2019, 7, 10),
        "avatar": "wave",
        "activity": "cooling",
        "notes": "朋友圈偶尔发学校门口那条土路。",
    },
    {
        "name": "邓师傅",
        "relationship_label": "修车师傅",
        "groups": ["邻居"],
        "circle_level": "occasional",
        "met_at": (2019, 5, 18),
        "avatar": "cactus",
        "activity": "cooling",
        "notes": "铺子在巷子口，墙上挂着一排旧内胎。",
    },
    {
        "name": "尹南",
        "relationship_label": "前同事",
        "groups": ["同事"],
        "circle_level": "normal",
        "met_at": (2021, 8, 2),
        "avatar": "coffee",
        "activity": "cooling",
        "notes": "做表格很快，快捷键按得噼里啪啦。",
    },
    {
        "name": "邱野",
        "relationship_label": "骑行认识",
        "groups": ["健身房"],
        "circle_level": "occasional",
        "met_at": (2022, 5, 14),
        "avatar": "mountain",
        "activity": "cooling",
        "notes": "车后座常年绑着一只打气筒。",
    },
    {
        "name": "崔小满",
        "relationship_label": "大学同学",
        "groups": ["老同学"],
        "circle_level": "normal",
        "met_at": (2018, 9, 8),
        "avatar": "star",
        "activity": "cooling",
        "notes": "毕业照那天借走过一件白衬衫。",
    },
    {
        "name": "何书",
        "relationship_label": "读书会同好",
        "groups": ["读书会"],
        "circle_level": "occasional",
        "met_at": (2023, 4, 23),
        "avatar": "book",
        "activity": "cooling",
        "notes": "书里从不折页，只用书签。",
    },
    {
        "name": "尚云",
        "relationship_label": "客户对接人",
        "groups": ["客户"],
        "circle_level": "normal",
        "met_at": (2022, 10, 9),
        "avatar": "camera",
        "activity": "cooling",
        "notes": "开会前会把要点打印出来，一人一份。",
    },
    {
        "name": "梁舟",
        "relationship_label": "邻居",
        "groups": ["邻居"],
        "circle_level": "occasional",
        "met_at": (2021, 7, 25),
        "avatar": "cat",
        "activity": "cooling",
        "notes": "搬家时借过一辆小推车。",
    },
    {
        "name": "任真",
        "relationship_label": "研究生同学",
        "groups": ["老同学"],
        "circle_level": "normal",
        "met_at": (2023, 9, 12),
        "avatar": "leaf",
        "activity": "cooling",
        "notes": None,
    },
    # --- cold（9 人，最近一次互动在 380–600 天前）---
    {
        "name": "贺兰",
        "relationship_label": "高中同学",
        "groups": ["高中"],
        "circle_level": "occasional",
        "met_at": (2017, 9, 1),
        "avatar": "bird",
        "activity": "cold",
        "notes": "字写得很小，笔记工整得像印的。",
    },
    {
        "name": "毕青",
        "relationship_label": "实习认识的",
        "groups": ["同事"],
        "circle_level": "occasional",
        "met_at": (2019, 6, 20),
        "avatar": "coffee",
        "activity": "cold",
        "notes": "实习那阵子每天一起吃食堂。",
    },
    {
        "name": "熊磊",
        "relationship_label": "篮球搭子",
        "groups": ["健身房"],
        "circle_level": "occasional",
        "met_at": (2020, 9, 12),
        "avatar": "bird",
        "activity": "cold",
        "notes": "三分很准，投篮前会拍两下球。",
    },
    {
        "name": "卫昭",
        "relationship_label": "大学同学",
        "groups": ["老同学"],
        "circle_level": "occasional",
        "met_at": (2018, 9, 8),
        "avatar": "moon",
        "activity": "cold",
        "notes": "毕业以后去了另一个城市。",
    },
    {
        "name": "邹然",
        "relationship_label": "摄影社朋友",
        "groups": ["摄影社"],
        "circle_level": "occasional",
        "met_at": (2021, 10, 16),
        "avatar": "camera",
        "activity": "cold",
        "notes": "只用定焦，包里塞着三台旧相机。",
    },
    {
        "name": "金禾",
        "relationship_label": "表姑",
        "groups": ["家人"],
        "circle_level": "occasional",
        "met_at": (2017, 2, 12),
        "avatar": "wave",
        "activity": "cold",
        "notes": "过年会在家族群里发一段语音。",
    },
    {
        "name": "霍东",
        "relationship_label": "客户对接人",
        "groups": ["客户"],
        "circle_level": "occasional",
        "met_at": (2020, 6, 30),
        "avatar": "book",
        "activity": "cold",
        "notes": "谈事喜欢约在上午，桌上总有一杯美式。",
    },
    {
        "name": "傅晓声",
        "relationship_label": "书店店员",
        "groups": ["读书会"],
        "circle_level": "occasional",
        "met_at": (2022, 2, 26),
        "avatar": "book",
        "activity": "cold",
        "notes": "在书店二楼的台面上留过一张推荐卡片。",
    },
    {
        "name": "彭涛",
        "relationship_label": "合作过的设计师",
        "groups": ["客户"],
        "circle_level": "occasional",
        "met_at": (2019, 11, 5),
        "avatar": "comet",
        "activity": "cold",
        "notes": "改稿很快，说话带一点南方口音。",
    },
]

#: 按主题分组的互动素材：``title`` / ``content`` / ``location``。
#: 句子不写人称，装配阶段按人名落地。
THEMED_INTERACTIONS: dict[str, list[dict[str, Any]]] = {
    "meal": [
        {"title": "一起吃火锅", "content": "锅底点了鸳鸯，辣的那半最后剩了大半。", "location": "学校旁边的火锅店"},
        {"title": "一起吃了顿家常菜", "content": "四个菜一个汤，米饭添了两次。", "location": "小区门口的小馆子"},
        {"title": "排队吃烤肉", "content": "排了四十分钟，肉是自己动手烤的。", "location": "校门口烤肉店"},
        {"title": "夜宵摊坐了一会儿", "content": "两串烤面筋，一瓶汽水，坐到摊主开始收凳子。", "location": None},
        {"title": "一起吃早饭", "content": "豆浆要的是不加糖的，油条掰成两半泡着吃。", "location": "巷口的早点铺"},
        {"title": "点了外卖在家吃", "content": "两个菜加一份汤，吃完把餐盒叠好放在门口。", "location": "家"},
        {"title": "一起包了饺子", "content": "馅里放了白菜和香菇，皮是买现成的。", "location": "家"},
        {"title": "中午一起去食堂", "content": "新出的那个窗口排了很长的队。", "location": "食堂二楼"},
        {"title": "吃了碗牛肉面", "content": "特意说了少放辣，汤喝完了。", "location": "老城区面馆"},
        {"title": "一起做饭", "content": "切菜的人负责切，掌勺的人嫌火太小。", "location": "家"},
        {"title": "下午吃了点心", "content": "买了两块桂花糕，纸袋上印着店名。", "location": "老城区"},
        {"title": "一起吃夜宵", "content": "炒粉加蛋，摊子支在路灯下面。", "location": None},
    ],
    "drink": [
        {"title": "一起喝咖啡", "content": "点的是浅烘的手冲，杯子先温过。", "location": "街角咖啡"},
        {"title": "排队买了奶茶", "content": "三分糖去冰，取餐号念到的时候愣了一下。", "location": "商场一楼"},
        {
            "title": "在小酒馆坐了一会儿",
            "content": "只点了一瓶，杯壁上的水珠滴到桌上。",
            "location": "livehouse 隔壁的小酒馆",
        },
        {"title": "去茶馆喝茶", "content": "泡的是去年的白茶，第二泡才出味道。", "location": "老城区茶馆"},
        {"title": "带了杯咖啡回去", "content": "外带杯上写了名字，少写了一个字。", "location": "公司楼下的咖啡馆"},
        {"title": "一起喝了点酒", "content": "配了一碟花生米，聊到店里换歌单。", "location": None},
        {
            "title": "在咖啡店坐了一下午",
            "content": "续了两杯，靠窗的位置下午会晒到太阳。",
            "location": "咖啡馆靠窗的位置",
        },
        {"title": "喝了一杯热可可", "content": "上面那层奶油没化开，勺子立在上面。", "location": "书店二楼"},
        {"title": "买了瓶汽水边走边喝", "content": "玻璃瓶要还，拎着空瓶走了一路。", "location": "江边步道"},
        {"title": "一起喝了手冲", "content": "磨豆的时候整个屋子都是香味。", "location": "家"},
        {"title": "喝茶聊了会儿", "content": "茶凉了才想起来续水。", "location": "办公室"},
        {"title": "路过便利店买了饮料", "content": "冰柜最里面那排是新上的口味。", "location": "小区门口的便利店"},
    ],
    "outdoor": [
        {"title": "一起去爬山", "content": "半路下起小雨，台阶上全是落叶。", "location": "北山步道"},
        {"title": "在湖边露营", "content": "帐篷搭了半小时，风绳一直不太服帖。", "location": "南湖公园"},
        {"title": "沿江骑了一段", "content": "骑到桥下面歇了会儿，链条上沾了泥。", "location": "江边绿道"},
        {"title": "早起跑了五公里", "content": "六点出门，路上只有扫地的和遛狗的。", "location": "滨江步道"},
        {"title": "去钓鱼", "content": "一上午只上来两条小的，都放回去了。", "location": "水库边"},
        {"title": "在公园里走了一圈", "content": "绕湖走的大圈，数了数一共七座桥。", "location": "南湖公园"},
        {"title": "去看了日落", "content": "爬到观景台的时候太阳刚好压在山脊上。", "location": "西山观景台"},
        {"title": "一起放风筝", "content": "线放得太快，缠到了旁边的树上。", "location": "江滩"},
        {"title": "逛了趟植物园", "content": "温室里湿度很大，镜头上全是雾。", "location": "植物园"},
        {"title": "在河边坐了一下午", "content": "带了两把折叠椅，看着水位慢慢下去。", "location": "江边步道"},
        {"title": "去郊外看油菜花", "content": "田埂很窄，走过去鞋上沾了一层黄粉。", "location": None},
        {"title": "夜爬了一趟", "content": "带着头灯上去，山顶风大得站不住。", "location": None},
    ],
    "culture": [
        {"title": "一起看电影", "content": "散场以后在影院门口站了一会儿，字幕走完了才走。", "location": "老电影院"},
        {"title": "去看了摄影展", "content": "有一个系列全是黑白的，站在前面看了很久。", "location": "市美术馆"},
        {"title": "看了一场话剧", "content": "第二幕的布景换得很安静，几乎没听到声音。", "location": "小剧场"},
        {"title": "在书店待了一下午", "content": "翻完两本画册，最后买了一本薄的。", "location": "书店二楼"},
        {"title": "去听了场音乐现场", "content": "站在靠后的位置，返场唱了第一首。", "location": "livehouse"},
        {"title": "看了场老片子", "content": "胶片放映，中间断了一次，灯亮了几秒。", "location": None},
        {"title": "一起逛了博物馆", "content": "在青铜器那一层停了最久。", "location": "市博物馆"},
        {"title": "去看了画展", "content": "门口领了一张折页，出来的时候折痕已经很深。", "location": "市美术馆"},
        {"title": "听了场讲座", "content": "后排没什么人，提问环节只站起来了两个。", "location": "图书馆报告厅"},
        {"title": "去看了场民谣演出", "content": "台上只有一把吉他和一只凳子。", "location": None},
        {"title": "逛了旧书市", "content": "翻到一本扉页上有铅笔字的旧书。", "location": "旧书市"},
        {"title": "一起看了场纪录片", "content": "映后主创留了二十分钟回答问题。", "location": "独立放映空间"},
    ],
    "sport": [
        {"title": "一起打羽毛球", "content": "反手特别稳，球总落在底线里面。", "location": "体育馆"},
        {"title": "打了半场篮球", "content": "投进了一个很勉强的三分，自己都笑了。", "location": "学校球场"},
        {"title": "去游泳", "content": "游了八百米，中间靠边歇了两次。", "location": "体育馆泳池"},
        {"title": "去健身房练了腿", "content": "深蹲加了五公斤，最后一组做得很勉强。", "location": "健身房"},
        {"title": "一起玩桌游", "content": "剧本杀挑了最简单的那个本。", "location": None},
        {"title": "打了两个小时乒乓球", "content": "换了新胶皮，球转得厉害。", "location": "社区活动室"},
        {"title": "去操场跑步", "content": "跑到第四圈的时候开始下雨。", "location": "操场"},
        {"title": "一起打了场球", "content": "打到天黑，球都快看不见了。", "location": None},
        {"title": "去攀岩馆", "content": "那条最简单的线路试了三次才上去。", "location": "攀岩馆"},
        {"title": "打了几局台球", "content": "白球进袋两次，被笑了一路。", "location": "台球厅"},
        {"title": "跟着练了一节团课", "content": "垫子摆在最后一排，动作总慢半拍。", "location": "健身房"},
        {"title": "去滑了旱冰", "content": "扶着栏杆绕了两圈才敢松手。", "location": None},
    ],
    "work": [
        {"title": "一起开了个会", "content": "投影仪连了半天，会开到一半才接上。", "location": "公司三楼会议室"},
        {"title": "留下来加班", "content": "十点才走，楼下的自动门已经锁了一扇。", "location": "办公室"},
        {"title": "一起出差", "content": "赶早班高铁，在车上把材料的顺序对了一遍。", "location": "火车站"},
        {"title": "做了个项目复盘", "content": "白板上写了三列，最后擦掉只留了一行。", "location": "公司三楼会议室"},
        {"title": "一起去参加行业活动", "content": "会场发了胸牌和一本很厚的资料。", "location": "会展中心"},
        {"title": "对接了一下需求", "content": "来回改了四版，最后用的是第一版。", "location": "线上会议"},
        {"title": "一起吃了工作餐", "content": "盒饭是照人数订的，多出来两份。", "location": None},
        {"title": "赶了一版方案", "content": "改到凌晨，第二天又推翻重来。", "location": None},
        {"title": "去客户那边开会", "content": "提前半小时到，在楼下又过了一遍要点。", "location": "客户公司"},
        {"title": "一起整理了数据", "content": "表格里有一列日期格式一直对不齐。", "location": "办公室"},
        {"title": "参加了部门例会", "content": "轮到自己汇报的时候话筒没电了。", "location": "公司三楼会议室"},
        {"title": "出差回来那天", "content": "飞机晚点两个小时，在候机厅把报告写完了。", "location": "机场"},
    ],
    "study": [
        {"title": "一起在图书馆自习", "content": "对面那桌一直在转笔，声音很轻。", "location": "图书馆"},
        {"title": "准备考试", "content": "把错题抄了一遍，用了半本活页纸。", "location": "图书馆三楼"},
        {"title": "聊了聊论文", "content": "开题的方向被建议换一个更小的切口。", "location": "教研室"},
        {"title": "去听了答辩", "content": "评委问了三个问题，第三个答得有点久。", "location": "教学楼报告厅"},
        {"title": "一起听了场讲座", "content": "讲的是一套很新的方法，笔记记了两页。", "location": "图书馆报告厅"},
        {"title": "帮改了摘要", "content": "摘要压到三百字以内，删掉了两个例子。", "location": None},
        {"title": "一起准备开题", "content": "参考书目列了二十几条，最后只用了八条。", "location": "实验室"},
        {"title": "在自习室待到很晚", "content": "十一点锁门，收拾东西的时候整层只剩两盏灯。", "location": "自习室"},
        {"title": "一起过了遍课件", "content": "有一页的公式一直没推明白，先记下来了。", "location": None},
        {"title": "去请教了问题", "content": "五分钟讲完，又顺手推荐了两篇文章。", "location": "办公室"},
        {"title": "一起做课程作业", "content": "分工到半夜，最后合并的时候格式全乱了。", "location": None},
        {"title": "借了几本书", "content": "有三本在架上，还有两本预约到下个月。", "location": "图书馆"},
    ],
    "family": [
        {"title": "回家吃了顿饭", "content": "炖了一锅汤，从中午就开始在灶上煨。", "location": "家"},
        {"title": "一起过了个节", "content": "桌上摆了一盘切好的月饼，谁都只吃了半块。", "location": "家"},
        {"title": "一起去买菜", "content": "在菜市场转了两圈，为了几毛钱又走回第一家。", "location": "社区菜市场"},
        {"title": "帮忙修了个东西", "content": "水龙头换了垫圈，工具是跟邻居借的。", "location": "家"},
        {"title": "陪去了一趟医院", "content": "早上七点去排队，挂号机前排了十几个人。", "location": "市第一医院"},
        {"title": "一起收拾了屋子", "content": "翻出来一箱旧照片，坐在地上看了半天。", "location": "家"},
        {"title": "打了个视频电话", "content": "信号不太好，说了两遍才听清。", "location": None},
        {"title": "一起包了粽子", "content": "叶子是提前泡好的，绳子绑得松紧不一。", "location": "家"},
        {"title": "去亲戚家串门", "content": "带了一箱水果，坐下就被塞了一碗糖水。", "location": "亲戚家"},
        {"title": "一起看老照片", "content": "有一张背面写着年份，字已经褪了。", "location": "家"},
        {"title": "去接了趟站", "content": "车晚了二十分钟，出站口的人越站越多。", "location": "火车站"},
        {"title": "一起吃了顿早饭", "content": "煮了粥，配的是自家腌的萝卜。", "location": "家"},
    ],
    "trip": [
        {"title": "去周边玩了两天", "content": "住的是民宿，院子里有一棵很大的桂花树。", "location": "民宿"},
        {"title": "赶了一趟火车", "content": "检票口快关了才跑到，行李是拎着上车的。", "location": "火车站"},
        {"title": "一起去了趟古镇", "content": "巷子很窄，两边都在卖同一种糕点。", "location": "古镇老街"},
        {"title": "自驾去看了海", "content": "开了四个小时，到的时候正好退潮。", "location": None},
        {"title": "在民宿住了一晚", "content": "晚上院子里点了一圈小灯，坐着聊到很晚。", "location": "民宿"},
        {"title": "去泡了温泉", "content": "池子边上有积雪，出来的时候头发上结了霜。", "location": "温泉度假区"},
        {"title": "坐大巴去了一趟县城", "content": "车上放着老电影，音量开得很大。", "location": None},
        {"title": "一起去爬了那座山", "content": "山顶有卖泡面的小摊，热水要另外算钱。", "location": "北山"},
        {"title": "在湖边住了两天", "content": "早上起来雾很大，对岸的树只剩一个轮廓。", "location": "湖边民宿"},
        {"title": "赶了趟早班机", "content": "四点就出门了，机场的早餐铺刚开灯。", "location": "机场"},
        {"title": "一起逛了当地的市场", "content": "买了两斤橘子和一袋现炒的栗子。", "location": "老城区"},
        {"title": "去了趟海边", "content": "捡了半袋贝壳，回来以后放在窗台上。", "location": None},
    ],
    "chat": [
        {"title": "视频通话", "content": "聊了一个多小时，中间去厨房烧了壶水。", "location": None},
        {"title": "聊到很晚", "content": "从工作聊到以前住的那栋楼，快一点才挂。", "location": None},
        {"title": "聊了聊近况", "content": "说了说最近的安排，也问了问家里的情况。", "location": None},
        {"title": "打了个电话", "content": "说到一半信号断了，又打回去接着讲。", "location": None},
        {"title": "聊到工作变动", "content": "在考虑换一个方向，还没有跟家里说。", "location": None},
        {"title": "发了几条消息", "content": "把之前拍的几张照片发了过去。", "location": None},
        {"title": "一起吃了饭慢慢聊", "content": "从天气聊到房子的租期，菜都凉了。", "location": "街角咖啡"},
        {"title": "在楼下站着聊了会儿", "content": "谁都没有先说要走，站到路灯亮起来。", "location": "小区门口"},
        {"title": "聊了聊接下来的打算", "content": "说想先把手上这件事做完，再说别的。", "location": None},
        {"title": "聊起以前的事", "content": "说起第一次见面那天，记的时间完全对不上。", "location": None},
        {"title": "在微信上聊了几句", "content": "发过去一个链接，回了一句「回头看看」。", "location": None},
        {"title": "打了很久的电话", "content": "手机贴着耳朵都发烫了，还换了一次手。", "location": None},
    ],
}

#: 一个人自己的 24 条记录；``SELF_PERSON_KEY`` 由写入阶段解析成 is_self 那一行。
SOLO_INTERACTIONS: list[dict[str, Any]] = [
    {
        "date": (2026, 10, 4),
        "title": "一个人去看了场电影",
        "content": "散场以后在路边坐了一会儿，风很凉。",
        "location": "老电影院",
        "mood": "🌙",
    },
    {
        "date": (2026, 9, 27),
        "title": "把阳台收拾干净了",
        "content": "换了土，顺手把枯掉的叶子剪了。",
        "location": "家",
        "mood": "🌿",
    },
    {
        "date": (2026, 9, 14),
        "title": "跑完第一个十公里",
        "content": "最后一公里几乎是走完的，但没停。",
        "location": "滨江步道",
        "mood": "💪",
    },
    {
        "date": (2026, 8, 30),
        "title": "学会了做一道菜",
        "content": "按视频里的步骤炖了四十分钟，盐放晚了。",
        "location": "家",
        "mood": "😊",
    },
    {
        "date": (2026, 8, 8),
        "title": "把书桌整个清了一遍",
        "content": "抽屉里翻出三支写不出水的笔，都扔了。",
        "location": "家",
        "mood": "😌",
    },
    {
        "date": (2026, 7, 19),
        "title": "去看了个展",
        "content": "工作日下午人很少，在最后一间展厅坐了很久。",
        "location": "市美术馆",
        "mood": "🤔",
    },
    {
        "date": (2026, 6, 28),
        "title": "一个人去吃了火锅",
        "content": "点了小锅，服务员在对面放了一只玩偶。",
        "location": "商场四楼",
        "mood": "😄",
    },
    {
        "date": (2026, 6, 6),
        "title": "沿着江走了两个小时",
        "content": "从桥这头走到那头，回来的路上买了瓶水。",
        "location": "江边步道",
        "mood": "😌",
    },
    {
        "date": (2026, 5, 17),
        "title": "把夏天的衣服翻出来了",
        "content": "有两件领口松了，叠好放在最下面一层。",
        "location": "家",
        "mood": "😴",
    },
    {
        "date": (2026, 4, 26),
        "title": "一个人去了趟附近的小城",
        "content": "坐了四十分钟高铁，出站先找了家面馆。",
        "location": "火车站",
        "mood": "😮",
    },
    {
        "date": (2026, 4, 4),
        "title": "修好了台灯",
        "content": "换了个开关，拧螺丝的时候手滑掉了一颗。",
        "location": "家",
        "mood": "💪",
    },
    {
        "date": (2026, 3, 15),
        "title": "写了一晚上字",
        "content": "把去年的事按月份列了一遍，写满了两页纸。",
        "location": "家",
        "mood": "🌙",
    },
    {
        "date": (2026, 2, 22),
        "title": "去了一趟医院",
        "content": "只是复查，报告要三天后才能取。",
        "location": "市第一医院",
        "mood": "😔",
    },
    {
        "date": (2026, 1, 30),
        "title": "搬家",
        "content": "书装了六个纸箱，搬到三楼的时候肩带断了一根。",
        "location": "新住处",
        "mood": "😴",
    },
    {
        "date": (2026, 1, 1),
        "title": "新年第一天没出门",
        "content": "把窗玻璃擦了，晚上听到外面零星几声鞭炮。",
        "location": "家",
        "mood": "😊",
    },
    {
        "date": (2025, 12, 21),
        "title": "冬至那天自己包了饺子",
        "content": "和面的时候水加多了，又补了半碗面粉。",
        "location": "家",
        "mood": "🥰",
    },
    {
        "date": (2025, 11, 29),
        "title": "一个人在livehouse听了一晚",
        "content": "靠墙站着，散场以后耳朵里还在响。",
        "location": "livehouse",
        "mood": "🎬",
    },
    {
        "date": (2025, 11, 8),
        "title": "把相机拿去清了灰",
        "content": "师傅说传感器上有一小块，取景的时候才看得见。",
        "location": "老城区",
        "mood": "📷",
    },
    {
        "date": (2025, 10, 19),
        "title": "沿着老城区走了一下午",
        "content": "拍了一卷，冲出来有一半是废片。",
        "location": "老城区",
        "mood": "📷",
    },
    {
        "date": (2025, 9, 27),
        "title": "给自己买了个小蛋糕",
        "content": "最小的那种，插了一根蜡烛又吹了。",
        "location": "家",
        "mood": "🎂",
    },
    {
        "date": (2025, 9, 6),
        "title": "早起去公园跑了三圈",
        "content": "跑完在长椅上坐着，看别人打太极。",
        "location": "南湖公园",
        "mood": "💪",
    },
    {
        "date": (2025, 8, 16),
        "title": "把夏天的照片导了出来",
        "content": "选了十二张洗成小尺寸的，夹在书里。",
        "location": "家",
        "mood": "😌",
    },
    {
        "date": (2025, 7, 20),
        "title": "一个人去看了场话剧",
        "content": "座位在最后一排，散场跟着人流走出去。",
        "location": "小剧场",
        "mood": "🎬",
    },
    {
        "date": (2025, 6, 14),
        "title": "重新开始记东西",
        "content": "买了个本子，第一页只写了日期。",
        "location": "街角咖啡",
        "mood": "☕",
    },
]

#: 互动 ``location`` 可用的地点名；与既有地点（南湖公园、学校后街、老城区……）不重复。
EXTRA_PLACES: list[str] = [
    "公司三楼会议室",
    "公司楼下的咖啡馆",
    "会展中心",
    "客户公司",
    "机场",
    "火车站",
    "社区菜市场",
    "市第一医院",
    "亲戚家",
    "新住处",
    "北山步道",
    "西山观景台",
    "江边绿道",
    "江滩",
    "水库边",
    "植物园",
    "古镇老街",
    "温泉度假区",
    "湖边民宿",
    "小剧场",
    "独立放映空间",
    "市博物馆",
    "图书馆报告厅",
    "自习室",
    "教研室",
    "教学楼报告厅",
    "社区活动室",
    "攀岩馆",
    "台球厅",
    "健身房",
    "体育馆泳池",
    "学校球场",
    "食堂二楼",
    "巷口的早点铺",
    "小区门口的小馆子",
    "老城区面馆",
    "老城区茶馆",
    "商场一楼",
    "商场四楼",
    "小区门口的便利店",
    "线上会议",
    "livehouse 隔壁的小酒馆",
    "咖啡馆靠窗的位置",
]

__all__ = [
    "EXTRA_GROUPS",
    "EXTRA_PEOPLE",
    "EXTRA_PLACES",
    "SELF_PERSON_KEY",
    "SOLO_INTERACTIONS",
    "THEMED_INTERACTIONS",
]
